#!/sbin/sh

. "$env"

print "Отключение принудительного шифрования в fstab..."

found_fstab=false

for fstab in fstab.*; do
	[ -f "$fstab" ] || continue
	print "Найден fstab: $fstab"
	sed -i "
		s/\b\(forceencrypt\|forcefdeorfbe\)=/encryptable=/g
	" "$fstab"
	found_fstab=true
done

$found_fstab || print "Не найден fstab!"

exit 0
